<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Check  Money order_billing-address-sa_4ac8d0</name>
   <tag></tag>
   <elementGuidId>b989cb8e-553a-437d-9b86-4a7147a3102d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing-address-same-as-shipping-checkmo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billing-address-same-as-shipping-checkmo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;My billing and shipping address are the same&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df0af16e-fbf1-4644-964c-1dfb9bf965bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f0d60096-f25d-4bce-b2af-2360508269ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing-address-same-as-shipping</value>
      <webElementGuid>2e2031ba-c4e9-4d63-b7aa-2fdf08763953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>checked: isAddressSameAsShipping, click: useShippingAddress, attr: {id: 'billing-address-same-as-shipping-' + getCode($parent)}</value>
      <webElementGuid>939e78fb-fd16-4249-9bb8-98c8da8488ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing-address-same-as-shipping-checkmo</value>
      <webElementGuid>5a3cee2a-4516-4be3-a513-dca19cb6a0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing-address-same-as-shipping-checkmo&quot;)</value>
      <webElementGuid>f356fe6c-92ae-4574-8d41-195a0da95d0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing-address-same-as-shipping-checkmo']</value>
      <webElementGuid>b86e62ab-bb40-458f-b3a8-945fff6e8fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-payment-method-load']/div/div/div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>35564d97-2016-4c4a-8c1a-2c4caec892f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>d9c9ca63-258c-40cf-b22d-0c60b1302726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'billing-address-same-as-shipping' and @id = 'billing-address-same-as-shipping-checkmo']</value>
      <webElementGuid>8b24b02b-30e4-4309-bda6-fa1ba491a00e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
